# Generated by Django 4.2.7 on 2024-03-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sthis_app', '0002_rename_full_name_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Name',
            new_name='full_name',
        ),
    ]
