# Generated by Django 4.2.7 on 2024-03-16 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sthis_app', '0003_rename_name_profile_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='full_name',
            new_name='first_name',
        ),
    ]
