# Generated by Django 4.2.7 on 2024-03-16 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sthis_app', '0005_p_delete_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='P',
            new_name='User',
        ),
    ]
