# Generated by Django 4.2.7 on 2024-03-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sthis_app', '0009_alter_location_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='culture',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='location',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
    ]
