# Generated by Django 4.2.7 on 2024-03-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sthis_app', '0010_alter_location_culture_alter_location_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='add',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
