# Generated by Django 4.2.7 on 2024-03-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sthis_app', '0011_alter_location_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='imapct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ei', models.IntegerField()),
                ('ce', models.IntegerField()),
                ('cp', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
